DELETE FROM CALIFICACIONENTITY;
ALTER TABLE CALIFICACIONENTITY ALTER COLUMN id RESTART WITH 1;

DELETE FROM PLATOENTITY;
ALTER TABLE PLATOENTITY ALTER COLUMN id RESTART WITH 1;

DELETE FROM PUNTOENTITY;
ALTER TABLE PUNTOENTITY ALTER COLUMN id RESTART WITH 1;

DELETE FROM TARJETAENTITY;
ALTER TABLE TARJETAENTITY ALTER COLUMN id RESTART WITH 1;

DELETE FROM DOMICILIOENTITY;
ALTER TABLE DOMICILIOENTITY ALTER COLUMN id RESTART WITH 1;

DELETE FROM RESERVAENTITY;
ALTER TABLE RESERVAENTITY ALTER COLUMN id RESTART WITH 1;

DELETE FROM MESAENTITY;
ALTER TABLE MESAENTITY ALTER COLUMN id RESTART WITH 1;

DELETE FROM SUCURSALENTITY_CLIENTEENTITY;

DELETE FROM CLIENTEENTITY_SUCURSALENTITY;

DELETE FROM CLIENTEENTITY;
ALTER TABLE CLIENTEENTITY ALTER COLUMN id RESTART WITH 1;

DELETE FROM SUCURSALENTITY;
ALTER TABLE SUCURSALENTITY ALTER COLUMN id RESTART WITH 1;
